---
- name: installa dipendenze
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
- name: aggiungi chiave GPG
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
- name: aggiungi repository docker
  apt_repository:
    repo: deb https://download.docker.com/linux/debian {{ansible_distribution_release}} stable
    state: present
- name: installa docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3-pip
- name: assicurati che docker sia attivo
  service:
    name: docker
    state: started
    enabled: yes
- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-linux-aarch64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

