---
# tasks file for setup-raspbee
- name: Enable uart
  lineinfile:
    path: /boot/firmware/config.txt
    state: present
    line: 'enable_uart=1'
  notify:
  - Reboot
- name: Setup dtoverlay
  lineinfile:
    path: /boot/firmware/config.txt
    state: present
    line: 'dtoverlay=disable-bt'
  notify:
  - Reboot
- name: Would you like a login shell accessible over serial? NO
  ansible.builtin.command: raspi-config nonint do_serial_cons 1
  notify:
  - Reboot
- name: Would you like the serial port hardware to be enabled? → Yes
  ansible.builtin.command: raspi-config nonint do_serial_hw 0
  notify:
  - Reboot