---
- name: setup vpn
  debug:
    msg: 'yolo'
- name: Ensure dependencies installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - openvpn
    - unzip
- name: Grab vpn files
  ansible.builtin.unarchive:
    src: https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip
    dest: /etc/openvpn
    remote_src: true
    owner: ansible
- name: Create auth.txt for openvpn
  ansible.builtin.copy:
    src: auth.txt
    dest: /etc/openvpn/auth.txt
- name: Create config for openvpn
  ansible.builtin.copy:
    src: fr538.nordvpn.com.tcp.ovpn
    dest: /etc/openvpn/nordvpn.conf

- name: Ensure config file is used
  ansible.builtin.lineinfile:
    path: /etc/default/openvpn
    line:  AUTOSTART="nordvpn"
  notify:
    - Reboot
- name: Ensure openvpn@nordvpn is running
  service:
    name: openvpn@nordvpn
    state: started